web_server_location       = "eastus"
web_server_rg             = "web-rg-dbg"
resource_prefix           = "web-server"
web_server_address_space  = "1.0.0.0/22"
web_server_name           = "dbg-web-02"
environment               = "production"
web_server_address_prefix = "1.0.1.0/24"